[project]
name = "nengin"
version = "0.2b"

readme = "README.md"

requires-python = ">= 3.13"
dependencies = ["pygame-ce>2.5.0"]

#TODO: check compat with older versions
description = "Object Oriented Wrapper for pygame-ce"