[project]
name = "nengin"
version = "0.1b"
requires-python = ">= 3.13"
dependencies = ["pygame-ce>2.5.0"]

description = "Object Oriented Wrapper for Pygame-CE"
readme = "README.md"

#TODO: check compat with older versions
